[package]
name = "ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
ssh2 = { git = "https://github.com/alexcrichton/ssh2-rs.git"}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0.0"
socket2 = "0.4.7"

