[package]
name = "remap"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gst = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package="gstreamer" }

[target.'cfg(windows)'.dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk3-rs"}
gdk = { git = "https://github.com/gtk-rs/gtk3-rs", package="gdk" }
gst-video = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package="gstreamer-video" }

[target.'cfg(unix)'.dependencies]
enigo = { git = "https://github.com/sganis/enigo" }



